### ISSUE TITLE
Dismiss notification after session with  open app is finished 

### ISSUE THREAD

**Issue by czarnyckm** [nyxkn/meditation#14]
After session and close the capp the meditation notification still remain. 
To dismiss it I must click on them and close the app again

**Comment by nyxkn** [comment]
I've now made the end notification dismiss itself automatically. And I've also made it so that when clicked it doesn't open the app but just dismisses itself. This should get it out of the way reasonably well.

Closing this as completed with 4809b3a31b8686cdcc29d1156c361ca67092bc4e
