### ISSUE TITLE
Intermediate bells

### ISSUE THREAD

**Issue by Mrnofish** [nyxkn/meditation#3]
Hello there,

thanks for making a new FOSS meditation timer. While I see one of the aims is to stay minimalist, I also appreciate that you're open to suggestions?

If this is the case, possibly the biggest feature missing at this time, and a showstopper in my opinion, is the complete absence of intermediate bells.

Having a periodic reminder to focus is useful for both users less advanced in their practice, but also expert ones that may be feeling particularly upset or otherwise experiencing a hard time concentrating.

**Comment by nyxkn** [comment]
Hey! Thanks for the interest and suggestion. A simple version of this with say one reminder at the middle of the session would be simple enough to add. If more customization is required it might get a bit too complex for what I had in mind. What kind of time intervals do you think are common or most useful? Is one bell in the middle enough or were you thinking of something more nuanced? Let me know what you think and I'll see what I can do!

**Comment by Mrnofish** [comment]
The purpose of the intermediate bells is to prevent the attention from wandering for long periods of time. To quote loosely from a teacher, some days you're like "today was really easy, time flew by" until you realize those 20 minutes were spent thinking about your meal, and none on actually paying attention.

How long an interval would be appropriate, depends both on the context and skill of the practitioner.

A beginner can be expected to take 5 minutes sessions because they might not be able to do more. Someone more advanced could still want to sit for 2, 3 or 5 minutes as an 'emergency' session, though.

In both cases you'd want frequent reminders, down to 30 or 15 seconds, probably.

In a different scenario, 1, 2, 5, 10, 15, 20, 30 minutes long intervals could be appropriate.

Off the top of my mind, Meditation Assistant and Insight Timer should both give the user a full-featured time picker. If I had to take a guess, I'd expect this to be the least amount of work while allowing maximum flexibility. I never coded Android apps, though.

There are other approaches I can think of, but not sure if they're worth the trouble.

Hope this helps in some way.

**Comment by nyxkn** [comment]
Thanks a lot for all the information!

In the latest version 1.3.0, I've implemented a basic version of intermediate bells where you can set the interval in any number of minutes. This seems to be the simplest method and yet very customizable. This is similar to what MeditationAssistant does (except they offer intervals down to the seconds precision).

Please feel free to give the new version a try and see what you think! You can find it now in the [releases page](https://github.com/nyxkn/meditation/releases/tag/1.3.0). Should also end up on fdroid eventually but might take a few days.

At the moment the bells are relying on notifications to be triggered, so the side-effect is that the screen has to wake up when it's time to play a bell. I'll attempt more subtle approaches in the future.
