### ISSUE TITLE
Themed app icons

### ISSUE THREAD

**Issue by devurandom** [nyxkn/meditation#8]
It would be nice if the app came with themed app icons:
* https://developer.android.com/about/versions/13/features#themed-app-icons
* https://developer.android.com/studio/write/create-app-icons#preview-themed-app-icons

**Comment by zrknlzr** [comment]
+1 on the feature request. Flutter doesn't support monochrome option in the pubspec file. But it should be possible with a line in `android/app/src/main/res/mipmap-anydpi-v26/ic_launcher.xml` like `<monochrome android:drawable="@mipmap/ic_launcher_monochrome" />` and some additional assets. I would have opened a PR but i can't create the monochrome icons without access to the high resolution icon source.

**Comment by nyxkn** [comment]
Hey, thanks for the info and links! This seems easily doable so I'll have a go.
